/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language } from '../types';

export const translations = {
  en: {
    title: 'Sudoku Quest',
    subtitle: 'Unlock difficulties sequentially by winning!',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    excellent: 'Excellent',
    locked: 'Locked',
    unlockCriteria: 'Unlock Criteria',
    locksEasyInfo: 'Always Unlocked! Start your journey here.',
    locksMediumInfo: 'Win at least 1 Easy level game to unlock.',
    locksHardInfo: 'Win at least 1 Medium level game to unlock.',
    locksExcellentInfo: 'Win at least 1 Hard level game to unlock.',
    startNewGame: 'Start New Game',
    resumeGame: 'Resume Game',
    difficulty: 'Difficulty',
    timer: 'Timer',
    paused: 'Paused',
    score: 'Score',
    undo: 'Undo',
    redo: 'Redo',
    erase: 'Erase',
    pencilMode: 'Pencil',
    hint: 'Hint',
    hintsLeft: 'Hints',
    checkErrors: 'Auto-Check Errors',
    newGame: 'New Game',
    solvedMessage: 'Congratulations! You solved the puzzle elegantly!',
    solvedSub: 'Go to the next level and unlock challenges!',
    quitGame: 'Quit Game',
    quitConfirm: 'Are you sure you want to quit the current game? Your current progress will be lost.',
    stats: 'Statistics',
    statsTitle: 'Your Sudoku Statistics',
    gamesPlayed: 'Games Played',
    gamesWon: 'Games Won',
    bestTime: 'Best Time',
    noRecord: 'No record yet',
    howToPlay: 'How to Play',
    rulesTitle: 'Sudoku Rules & Unlock Progress',
    rule1: 'Grid Layout: Fill the 9x9 grid with numbers from 1 to 9.',
    rule2: 'Row Rule: Each horizontal row must contain numbers 1 to 9 without repetition.',
    rule3: 'Column Rule: Each vertical column must contain numbers 1 to 9 without repetition.',
    rule4: '3x3 Block Rule: Each of the nine 3x3 subgrids must contain numbers 1 to 9 without repetition.',
    ruleUnlock: 'Sequential Unlocking: Win structured challenges to level up from Easy ➔ Medium ➔ Hard ➔ Excellent!',
    unlockedBadge: 'UNLOCKED',
    lockedBadge: 'LOCKED',
    close: 'Close',
    back: 'Back to Menu',
    clearAllStats: 'Reset Progress',
    clearStatsCheck: 'Are you sure you want to reset all game statistics and locks? This cannot be undone.',
    incorrectValue: 'Incorrect value!',
    perfect: 'Perfect!',
    errorLimitTitle: 'Game Over!',
    errorLimitMsg: 'You reached the error limit (3 errors). Try starting a new puzzle to sharpen your skills!',
    errors: 'Errors',
    noErrorsActive: 'Clean Sheet',
    activeNotes: 'Notes active',
    inactiveNotes: 'Notes inactive',
    musicOn: 'Sound effects on',
    musicOff: 'Sound effects off',
    classicTheme: 'Classic Light',
    midnightTheme: 'Midnight',
    sepiaTheme: 'Warm Sepia',
  },
  ta: {
    title: 'சுடோகு சவால் (Sudoku Grid)',
    subtitle: 'ஒவ்வொரு மட்டமாக வென்று, அடுத்தடுத்த கடின நிலைகளை அன்லாக் செய்யுங்கள்!',
    easy: 'எளியது (Easy)',
    medium: 'நடுத்தரம் (Medium)',
    hard: 'கடினம் (Hard)',
    excellent: 'மிகச்சிறப்பு (Excellent)',
    locked: 'பூட்டப்பட்டுள்ளது',
    unlockCriteria: 'அன்லாக் செய்யும் நிபந்தனை',
    locksEasyInfo: 'எப்போதும் திறந்திருக்கும்! உங்கள் விளையாட்டை இங்கிருந்து தொடங்குங்கள்.',
    locksMediumInfo: 'நடுத்தர நிலையைத் திறக்க குறைந்தபட்சம் 1 "எளியது" விளையாட்டில் வெல்ல வேண்டும்.',
    locksHardInfo: 'கடின நிலையைத் திறக்க குறைந்தபட்சம் 1 "நடுத்தரம்" விளையாட்டில் வெல்ல வேண்டும்.',
    locksExcellentInfo: 'மிகச்சிறப்பு நிலையைத் திறக்க குறைந்தபட்சம் 1 "கடினம்" விளையாட்டில் வெல்ல வேண்டும்.',
    startNewGame: 'புதிய ஆட்டம்',
    resumeGame: 'தொடரவும்',
    difficulty: 'கடின நிலை',
    timer: 'நேரம்',
    paused: 'நிறுத்தப்பட்டுள்ளது',
    score: 'மதிப்பெண்',
    undo: 'பின்செல்க (Undo)',
    redo: 'முன்செல்க (Redo)',
    erase: 'அழிப்பான் (Erase)',
    pencilMode: 'குறிப்பு (Pencil)',
    hint: 'உதவி (Hint)',
    hintsLeft: 'உதவிகள்',
    checkErrors: 'தவறுகளை உடனுக்குடன் காட்டு',
    newGame: 'புதிய ஆட்டம்',
    solvedMessage: 'வாழ்த்துகள்! நீங்கள் புதிரை மிகச்சிறப்பாக தீர்த்துவிட்டீர்கள்!',
    solvedSub: 'அடுத்த நிலைக்குச் சென்று புதிய சவால்களை வெல்லுங்கள்!',
    quitGame: 'ஆட்டத்திலிருந்து வெளியேறு',
    quitConfirm: 'தற்போதைய ஆட்டத்திலிருந்து வெளியேற வேண்டுமா? உங்கள் தற்போதைய முன்னேற்றம் அழிக்கப்படும்.',
    stats: 'விவரங்கள் (Stats)',
    statsTitle: 'உங்கள் விளையாட்டு விவரங்கள்',
    gamesPlayed: 'விளையாடிய ஆட்டங்கள்',
    gamesWon: 'வென்ற ஆட்டங்கள்',
    bestTime: 'சிறந்த நேரம்',
    noRecord: 'பதிவுகள் இல்லை',
    howToPlay: 'விளையாடுவது எப்படி',
    rulesTitle: 'விதிமுறைகள் மற்றும் அன்லாக் நிலைகள்',
    rule1: 'கட்ட வடிவமைப்பு: 9x9 கட்டத்தை 1 முதல் 9 வரையிலான எண்களால் நிரப்பவும்.',
    rule2: 'வரிசை விதி: ஒவ்வொரு கிடைமட்ட வரிசையிலும் 1 முதல் 9 வரையிலான எண்கள் மீண்டும் வராமல் இருக்க வேண்டும்.',
    rule3: 'நிரல் விதி: ஒவ்வொரு செங்குத்து நிரலிலும் 1 முதல் 9 வரையிலான எண்கள் மீண்டும் வராமல் இருக்க வேண்டும்.',
    rule4: '3x3 தொகுதி விதி: ஒன்பது 3x3 துணைக்கட்டங்களில் ஒவ்வொன்றிலும் 1 முதல் 9 வரையிலான எண்கள் மீண்டும் வராமல் இருக்க வேண்டும்.',
    ruleUnlock: 'அன்லாக் வரிசைமுறை: எளியது ➔ நடுத்தரம் ➔ கடினம் ➔ மிகச்சிறப்பு என விளையாடி வென்று புதிய நிலைகளைத் திறக்கலாம்!',
    unlockedBadge: 'அன்லாக் செய்யப்பட்டுள்ளது',
    lockedBadge: 'பூட்டப்பட்டுள்ளது',
    close: 'மூடுக',
    back: 'முதன்மைப் பக்கம்',
    clearAllStats: 'முன்னேற்றத்தை மீட்டமை',
    clearStatsCheck: 'அனைத்து புள்ளிவிவரங்களையும் மீட்டமைக்க வேண்டுமா? இதைத் திரும்பப் பெற முடியாது.',
    incorrectValue: 'தவறான எண்!',
    perfect: 'அருமை!',
    errorLimitTitle: 'ஆட்டம் முடிந்தது!',
    errorLimitMsg: 'நீங்கள் அதிகபட்ச பிழை வரம்பை (3 பிழைகள்) அடைந்துவிட்டீர்கள். உங்கள் திறமைகளை வளர்த்துக்கொள்ள புதிய ஆட்டத்தைத் தொடங்குங்கள்!',
    errors: 'பிழைகள்',
    noErrorsActive: 'பிழைகள் இல்லை',
    activeNotes: 'குறிப்புகள் செயல்படுகின்றன',
    inactiveNotes: 'குறிப்புகள் முடக்கப்பட்டுள்ளன',
    musicOn: 'ஒலி விளைவுகள் ஆன்',
    musicOff: 'ஒலி விளைவுகள் ஆஃப்',
    classicTheme: 'கிளாசிக் ஒளி',
    midnightTheme: 'மிட்நைட்',
    sepiaTheme: 'செபியா மிதவெப்பம்',
  }
};

export function getT(lang: Language) {
  return translations[lang];
}
